const Stats = ()=>{
    return (
        <>
        <div className="bg-gray-50 dark:bg-gray-900 p-8 min-h-[350px] flex flex-col items-center justify-center font-sans">
      <h2 className="text-gray-800 text-3xl font-bold mb-16 text-center dark:text-slate-200">Application Metrics</h2>
      <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl dark:text-slate-300 font-extrabold">5.4<span className="text-blue-600">M+</span></h3>
          <p className="text-base font-bold mt-4 dark:text-slate-300">Total Users</p>
          <p className="text-sm text-gray-500 mt-2">The total number of registered users on the platform.</p>
        </div>
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl dark:text-slate-300 font-extrabold">$80<span className="text-blue-600">K</span></h3>
          <p className="text-base font-bold dark:text-slate-300 mt-4">Revenue</p>
          <p className="text-sm text-gray-500 mt-2">The total revenue generated by the application.</p>
        </div>
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl dark:text-slate-300 font-extrabold">100<span className="text-blue-600">K</span></h3>
          <p className="text-base font-bold dark:text-slate-300 mt-4">Engagement</p>
          <p className="text-sm text-gray-500 mt-2">The level of user engagement with the application's content and features.</p>
        </div>
        <div className="text-center">
          <h3 className="text-gray-800 text-4xl dark:text-slate-300 font-extrabold">99.9<span className="text-blue-600">%</span></h3>
          <p className="text-base font-bold dark:text-slate-300 mt-4">Server Uptime</p>
          <p className="text-sm text-gray-500 mt-2">The percentage of time the server has been operational and available.</p>
        </div>
      </div>
    </div>
        </>
    )
}
export default Stats;